Repository UTDNebula/planner, pull requests merged in 2020-06, with the labels that each got.

#3 Initialize data store and routing
  .gitignore
  README.md
  docs/design.md
  docs/index.md
  docs/style.md
  package-lock.json
  package.json
  src/App.js
  src/courses/actions.js
  src/courses/reducers.js
  src/dummy_schedule.json
  src/firebase-config.js
  src/index.js
  src/landing/index.js
  src/lib/api/index.js
  src/lib/firebase-init.js
  src/lib/index.js
  src/lib/types.js
  src/planner/actions.js
  src/planner/index.js
  src/planner/reducers.js
  src/schedules/index.js
Labels: infrastructure

#15 Initialize TypeScript and prepare for component development
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/App.tsx
  src/courses/CourseCard.tsx
  src/courses/actions.js
  src/dummy_schedule.json
  src/firebase-config.js
  src/index.css
  src/index.tsx
  src/initial-data.tsx
  src/landing/index.tsx
  src/lib/index.js
  src/lib/index.ts
  src/lib/types.js
  src/lib/types.ts
  src/logo.svg
  src/planner/CourseSourceSidebar.tsx
  src/planner/SchedulePlanner.tsx
  src/planner/SemesterBlock.tsx
  src/planner/actions.ts
  src/planner/index.js
  src/planner/index.ts
  src/planner/reducers.js
  src/react-app-env.d.ts
  src/schedules/index.js
  src/schedules/index.ts
  src/serviceWorker.ts
  src/setupTests.js
  tsconfig.json
Labels: enhancement, infrastructure

#16 Fix module errors in SchedulePlanner
  src/courses/actions.ts
  src/planner/SchedulePlanner.tsx
Labels: bug

#18 Fix missing ScheduleListPage components
  src/schedules/ScheduleList.tsx
  src/schedules/ScheduleListPage.tsx
Labels: bug

#23 Migrate components to Material-UI
  package-lock.json
  package.json
  src/courses/CourseCard.tsx
  src/planner/CourseSourceSidebar.tsx
  src/planner/SchedulePlanner.tsx
  src/planner/SchedulePlannerStyle.tsx
  src/planner/SemesterBlock.tsx
  src/styling.ts
Labels: infrastructure
