Repository UTDNebula/planner, pull requests merged in 2022-02, with the labels that each got.

#79 Adopt MIT License
  LICENSE
Labels: Type: Internal

#77 fix: Load correct user data
  modules/profile/userDataSlice.ts
  pages/app/index.tsx
Labels: Type: Bug Report

#104 Fix typos in the README
  README.md
Labels: Type: Documentation
